# Generated by Django 2.2.1 on 2019-06-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_field", "0003_customfield_mask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfield",
            name="default_value",
            field=models.CharField(
                blank=True,
                help_text="You may leave blank. For Boolean use True or False",
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="field_choices",
            field=models.CharField(
                blank=True,
                help_text="List the choices you want displayed, seperated by commas. This is only valid for Dropdown, Multiple, and Checkbox field types",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("t", "Text"),
                    ("a", "Large Text Field"),
                    ("i", "Integer"),
                    ("f", "Floating point decimal"),
                    ("b", "Boolean (Yes/No)"),
                    ("m", "Dropdown Choices"),
                    ("d", "Date"),
                    ("h", "Date Time"),
                ],
                default="t",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="mask",
            field=models.CharField(
                blank=True,
                help_text="You may leave blank. For user Jquery Mask, ex: '00/00/0000' for date.",
                max_length=5000,
            ),
        ),
    ]
